// data/mockTeamsData.ts
import { UserTeam } from "@/app/types/models_types/userType";
export const mockTeams = [
  {
    id: 1,
    name: "Echipa Marketing",
    icon: "📊",
    description:
      "Echipa responsabilă pentru campaniile de marketing și comunicare.",
    unreadCount: 3,
    members: [1, 2, 3, 5],
    channels: [
      { id: 101, name: "General", unreadCount: 1 },
      { id: 102, name: "Campanii 2025", unreadCount: 2 },
      { id: 103, name: "Social Media", unreadCount: 0 },
    ],
  },
  {
    id: 2,
    name: "Dezvoltare Produs",
    icon: "💻",
    description: "Echipa de dezvoltare software și design.",
    unreadCount: 8,
    members: [1, 3, 4, 6, 7],
    channels: [
      { id: 201, name: "General", unreadCount: 1 },
      { id: 202, name: "Frontend", unreadCount: 2 },
      { id: 203, name: "Backend", unreadCount: 5 },
      { id: 204, name: "Design", unreadCount: 0 },
    ],
  },
  {
    id: 3,
    name: "Resurse Umane",
    icon: "👥",
    description: "Echipa de HR și recrutare.",
    unreadCount: 0,
    members: [1, 5, 8],
    channels: [
      { id: 301, name: "General", unreadCount: 0 },
      { id: 302, name: "Recrutări", unreadCount: 0 },
      { id: 303, name: "Training", unreadCount: 0 },
    ],
  },
  {
    id: 4,
    name: "Suport Clienți",
    icon: "🛟",
    description: "Echipa de asistență și suport pentru clienți.",
    unreadCount: 12,
    members: [1, 2, 7, 8],
    channels: [
      { id: 401, name: "General", unreadCount: 5 },
      { id: 402, name: "Tichete urgente", unreadCount: 7 },
      { id: 403, name: "Feedback", unreadCount: 0 },
    ],
  },
  {
    id: 5,
    name: "Management",
    icon: "🏢",
    description: "Echipa de conducere și coordonare.",
    unreadCount: 1,
    members: [1, 6],
    channels: [
      { id: 501, name: "General", unreadCount: 1 },
      { id: 502, name: "Strategie", unreadCount: 0 },
      { id: 503, name: "Planificare", unreadCount: 0 },
    ],
  },
];

export const mockUsers: UserTeam[] = [
  {
    id: 1,
    name: "Ana Popescu",
    email: "ana.popescu@companie.ro",
    avatar: "/avatars/user1.jpg",
    status: "online",
    role: "Product Manager",
    department: "Dezvoltare",
  },
  {
    id: 2,
    name: "Mihai Ionescu",
    email: "mihai.ionescu@companie.ro",
    avatar: "/avatars/user2.jpg",
    status: "offline",
    role: "Marketing Specialist",
    department: "Marketing",
  },
  {
    id: 3,
    name: "Cristina Dumitrescu",
    email: "cristina.dumitrescu@companie.ro",
    avatar: "/avatars/user3.jpg",
    status: "busy",
    role: "Frontend Developer",
    department: "Dezvoltare",
  },
  {
    id: 4,
    name: "Alexandru Popa",
    email: "alexandru.popa@companie.ro",
    avatar: "/avatars/user4.jpg",
    status: "away",
    role: "Backend Developer",
    department: "Dezvoltare",
  },
  {
    id: 5,
    name: "Elena Stancu",
    email: "elena.stancu@companie.ro",
    avatar: "/avatars/user5.jpg",
    status: "online",
    role: "HR Manager",
    department: "Resurse Umane",
  },
  {
    id: 6,
    name: "Andrei Munteanu",
    email: "andrei.munteanu@companie.ro",
    avatar: "/avatars/user6.jpg",
    status: "offline",
    role: "CEO",
    department: "Management",
  },
  {
    id: 7,
    name: "Diana Radu",
    email: "diana.radu@companie.ro",
    avatar: "/avatars/user7.jpg",
    status: "online",
    role: "UI/UX Designer",
    department: "Design",
  },
  {
    id: 8,
    name: "Victor Stan",
    email: "victor.stan@companie.ro",
    avatar: "/avatars/user8.jpg",
    status: "online",
    role: "Customer Support",
    department: "Suport",
  },
];

export const mockEvents = [
  {
    id: 101,
    teamId: 1,
    channelId: 101,
    title: "Planificare campanie Q1",
    description: "Discuție despre strategia de marketing pentru Q1 2025",
    date: "2025-01-10T10:00:00",
    duration: 60, // minute
    attendees: [1, 2, 5],
  },
  {
    id: 102,
    teamId: 1,
    channelId: 102,
    title: "Review campanii sociale",
    description: "Analiză a performanței campaniilor de social media",
    date: "2025-01-15T14:30:00",
    duration: 45,
    attendees: [1, 2, 3],
  },
  {
    id: 201,
    teamId: 2,
    channelId: 201,
    title: "Sprint Planning",
    description: "Planificarea sprintului pentru următoarele 2 săptămâni",
    date: "2025-01-08T09:00:00",
    duration: 90,
    attendees: [1, 3, 4, 7],
  },
  {
    id: 202,
    teamId: 2,
    channelId: 202,
    title: "Code Review",
    description: "Review pentru noile componente Frontend",
    date: "2025-01-12T11:00:00",
    duration: 60,
    attendees: [1, 3, 7],
  },
  {
    id: 301,
    teamId: 3,
    channelId: 301,
    title: "Evaluare candidați",
    description: "Discuție despre candidații intervievați săptămâna trecută",
    date: "2025-01-09T15:00:00",
    duration: 60,
    attendees: [1, 5],
  },
  {
    id: 401,
    teamId: 4,
    channelId: 401,
    title: "Training suport clienți",
    description: "Sesiune de training pentru noile proceduri de suport",
    date: "2025-01-11T13:00:00",
    duration: 120,
    attendees: [1, 2, 8],
  },
  {
    id: 501,
    teamId: 5,
    channelId: 501,
    title: "Ședință de strategie",
    description: "Planificare strategică pentru Q1 2025",
    date: "2025-01-14T09:30:00",
    duration: 180,
    attendees: [1, 6],
  },
];

export const mockFiles = [
  {
    id: 1001,
    teamId: 1,
    channelId: 101,
    name: "Strategie marketing 2025.pdf",
    type: "pdf",
    size: "2.4 MB",
    uploadedBy: 1,
    uploadedAt: "2024-12-15T14:20:00",
    url: "#",
  },
  {
    id: 1002,
    teamId: 1,
    channelId: 102,
    name: "Social Media Calendar Q1.xlsx",
    type: "excel",
    size: "1.8 MB",
    uploadedBy: 2,
    uploadedAt: "2024-12-18T09:45:00",
    url: "#",
  },
  {
    id: 1003,
    teamId: 1,
    channelId: 103,
    name: "Facebook Ads Performance.pptx",
    type: "powerpoint",
    size: "5.2 MB",
    uploadedBy: 2,
    uploadedAt: "2024-12-20T16:30:00",
    url: "#",
  },
  {
    id: 2001,
    teamId: 2,
    channelId: 201,
    name: "Product Roadmap 2025.pdf",
    type: "pdf",
    size: "3.1 MB",
    uploadedBy: 1,
    uploadedAt: "2024-12-10T11:15:00",
    url: "#",
  },
  {
    id: 2002,
    teamId: 2,
    channelId: 202,
    name: "UI Components Library.fig",
    type: "figma",
    size: "8.7 MB",
    uploadedBy: 7,
    uploadedAt: "2024-12-12T15:40:00",
    url: "#",
  },
  {
    id: 2003,
    teamId: 2,
    channelId: 203,
    name: "API Documentation.md",
    type: "markdown",
    size: "256 KB",
    uploadedBy: 4,
    uploadedAt: "2024-12-17T14:00:00",
    url: "#",
  },
  {
    id: 2004,
    teamId: 2,
    channelId: 204,
    name: "New App Design.png",
    type: "image",
    size: "4.3 MB",
    uploadedBy: 7,
    uploadedAt: "2024-12-19T10:20:00",
    url: "#",
  },
  {
    id: 3001,
    teamId: 3,
    channelId: 301,
    name: "Employee Handbook 2025.pdf",
    type: "pdf",
    size: "5.8 MB",
    uploadedBy: 5,
    uploadedAt: "2024-12-14T09:30:00",
    url: "#",
  },
  {
    id: 4001,
    teamId: 4,
    channelId: 401,
    name: "Support Protocols.docx",
    type: "word",
    size: "1.2 MB",
    uploadedBy: 8,
    uploadedAt: "2024-12-13T13:20:00",
    url: "#",
  },
  {
    id: 5001,
    teamId: 5,
    channelId: 501,
    name: "Annual Report 2024.pdf",
    type: "pdf",
    size: "12.5 MB",
    uploadedBy: 6,
    uploadedAt: "2024-12-22T16:45:00",
    url: "#",
  },
];
